[Example App] Remove old example App
Polidea/RxBluetoothKit pull request #385
Opened 2020-10-16 11:00 UTC by mpiechocki

Removed old example app and added a blank new one. Got rid of the `Main.storyboard` ;)

2020-10-16 11:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Polidea/RxBluetoothKit?pullRequest=385) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Polidea/RxBluetoothKit?pullRequest=385) before we can accept your contribution.<br/><hr/>**Mikołaj Piechocki** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Polidea/RxBluetoothKit?pullRequest=385) it.</sub>

2020-10-23 08:05 UTC, minixT requested changes
Reviewed. Looks good. Please see my comments and let me know what will be the part of this PR and what you will change in the next steps.

2020-10-23 08:57 UTC, mpiechocki commented on ExampleApp/ExampleApp/Screens/Central/CentralViewController.swift
> +            .subscribe(onNext: { [weak self] in
I think I'll add a basic, generic way to handle all errors (like an alert just saying what's the error). For me, the purpose of this app should be to show how to use the library in a simple way, without too much clutter. What do you think?

2020-10-23 09:02 UTC, mpiechocki commented on ExampleApp/ExampleApp/Screens/Peripheral/PeripheralViewController.swift
> +              let value = peripheralView.valueTextField.text else { return }
Actually, I think we should just leave it as simple as can be (and maybe add a note in readme, that you have to enter a proper uuid strings). Again, I think we should keep the app as simple as can be, believing that people running this app would be just developers trying to get to know how to use the lib :)

2020-10-23 09:02 UTC, minixT commented on ExampleApp/ExampleApp/Screens/Central/CentralViewController.swift
> +            .subscribe(onNext: { [weak self] in
I think simple alert will be enough.

2020-10-23 09:17 UTC, mpiechocki commented on ExampleApp/ExampleApp/Screens/Peripheral/PeripheralViewController.swift
> +            .flatMap { [manager] in manager.startAdvertising($0.advertisingData) }
I beleive so :)
both `PeripheralViewController` the closure have the reference to manager, so there's no cycle. Quick testing with Memory Graph tool proves it :)

2020-10-23 09:18 UTC, mpiechocki commented on ExampleApp/ExampleApp/Screens/Central/CentralViewController.swift
> +            .subscribe(onNext: { [weak self] in
I'll add a generic alert in this PR

2020-10-23 11:56 UTC, mpiechocki commented
@minixT fyi, I pushed some commits with your suggestions :)

2020-10-26 08:52 UTC, minixT approved these changes

2020-11-02 06:46 UTC, closed without merging